rbls {
  spamhaus_zen {
    symbol = "RBL_SPAMHAUS_ZEN";
    rbl = "zen.spamhaus.org";
    checks = ["from", "received"];
    symbols_prefixes = {
      received = "RECEIVED";
      from = "RBL";
    }
    returncodes {
      RBL_SPAMHAUS_SBL = "127.0.0.2";
      RBL_SPAMHAUS_CSS = "127.0.0.3";
      RBL_SPAMHAUS_XBL = ["127.0.0.4", "127.0.0.5", "127.0.0.6", "127.0.0.7"];
      RBL_SPAMHAUS_PBL = ["127.0.0.10", "127.0.0.11"];
      RBL_SPAMHAUS_DROP = "127.0.0.9";
    }
  }
}
