CREATE TABLE IF NOT EXISTS mail_stats (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  stat_date DATE NOT NULL,
  sent INTEGER NOT NULL DEFAULT 0,
  received INTEGER NOT NULL DEFAULT 0,
  bounced INTEGER NOT NULL DEFAULT 0,
  spam_caught INTEGER NOT NULL DEFAULT 0,
  UNIQUE(stat_date)
);
